name: Meson CI

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: Windows MSVC Release,
            os: windows-latest,
            msvc: true,
            buildtype: release,
            args: '-Ddefault_library=static --wrap-mode=forcefallback'
          }
          - {
            name: Windows MinGW Release,
            os: windows-latest,
            msvc: false,
            buildtype: release,
            args: ''
          }
          - {
            name: Ubuntu Debug,
            os: ubuntu-latest,
            buildtype: debugoptimized,
            args: ''
          }
          - {
            name: Ubuntu Release,
            os: ubuntu-latest,
            buildtype: release,
            args: ''
          }
          - {
            name: macOS Debug,
            os: macos-latest,
            buildtype: debugoptimized,
            args: ''
          }
          - {
            name: macOS Release,
            os: macos-latest,
            buildtype: release,
            args: -Ddefault_library=static
          }

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Setup Meson
        run: |
          python -m pip install --upgrade pip
          pip install meson

      - name: Setup MSVC
        if: matrix.config.os == 'windows-latest' && matrix.config.msvc == true
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install dependencies
        shell: bash
        run: |
          case "${{ matrix.config.os }}" in
            windows-*)
              choco install ninja nasm
              ;;
            macos-*)
              brew install nasm ninja pkg-config
              ;;
            ubuntu-*)
              sudo apt-get update
              sudo apt-get install ninja-build build-essential pkg-config nasm libfreetype6-dev libfontconfig1-dev libharfbuzz-dev libfribidi-dev
              ;;
          esac

      - name: Set up WrapDB
        if: matrix.config.os == 'windows-latest' || matrix.config.os == 'macos-latest'
        run: |
          meson wrap update-db

      - name: Configure
        run: meson setup build ${{ matrix.config.args }} -Dbuildtype=${{ matrix.config.buildtype }}

      - name: Build
        run: meson compile -C build

      - name: Dump Meson Debug Info
        if: failure()
        run: cat build/meson-logs/meson-log.txt
